Collapsed control flow categories.

diff --git a/zero-to-sysadmin/2_advanced_topics/09_bash_scripting b/zero-to-sysadmin/2_advanced_topics/09_bash_scripting
--- a/zero-to-sysadmin/2_advanced_topics/09_bash_scripting
+++ b/zero-to-sysadmin/2_advanced_topics/09_bash_scripting
@@ -88,138 +88,136 @@ CHAPTER 9 - COMMAND LINE PROGRAMMING
 
 
 
-- Program Flow Control
+- The if Statement
 
-    - The if Statement
+    - The syntax for the 'if' statement is:
 
-        - The syntax for the 'if' statement is:
-
-            if condition1; then list1; [ elif condition2; then list2; ] ... [ else list3; ] fi
+        if condition1; then list1; [ elif condition2; then list2; ] ... [ else list3; ] fi
 
 
 
-    - true and false
+- true and false
 
-        - The 'true' command always produces a return code of 0, and the 'false' command always
-            produces a return code of 1.
+    - The 'true' command always produces a return code of 0, and the 'false' command always
+        produces a return code of 1.
 
-            # Return code 0
-            $ true ; echo $?
-            0
+        # Return code 0
+        $ true ; echo $?
+        0
 
-            # Return code 1
-            $ false ; echo $?
-            1
+        # Return code 1
+        $ false ; echo $?
+        1
 
-            # 'true' with operators
-            $ true && echo "True" || echo "False"
-            True
+        # 'true' with operators
+        $ true && echo "True" || echo "False"
+        True
 
-            # 'false' with operators
-            $ false && echo "True" || echo "False"
-            False
-
-
-
-    - Logical Operators
-
-        - The functional syntax of these comparison operators is 1 or 2 arguments with an 
-            operator that are placed within square braces.  We have a 'list' of program
-            statements that are executed if the statement is true, and an optional list
-            of program stratements if the condition is false.
-
-            # If only
-            if [ arg1 operator arg2 ] ; then list
-
-            # If/else
-            if [ arg1 operator arg2 ] ; then list ; else list ; fi
-
-
-        - The square braces are the traditional Bash symbols that are equivalent to the   
-            'test' command.  
-
-            # If only
-            if test arg1 operator arg2 ; then list
-
-
-        - There is also a more recent double square bracket syntax that has a few 
-            advantages.
-
-            # If only
-            if [[ arg1 operator arg2 ]] ; then list
+        # 'false' with operators
+        $ false && echo "True" || echo "False"
+        False
 
 
 
-    - File Operators
+- Logical Operators
 
-        Operators
-        ----------------------------------------------------------------------------------------
-        -a filename            True if file exists
-        -b filename            True if file exists and is block special file (ie /dev/sda1)
-        -c filename            True if file exists and is character special file (ie /dev/TTY1)
-        -d filename            True if file exists and is a directory
-        -e filename            True if file exists (same as -a)
+    - The functional syntax of these comparison operators is 1 or 2 arguments with an 
+        operator that are placed within square braces.  We have a 'list' of program
+        statements that are executed if the statement is true, and an optional list
+        of program stratements if the condition is false.
 
-        -f filename            True if file exists and is regular file
-        -g filename            True if file exists and is set-group-id, SETGID
-        -h filename            True if file exists and is symbolic link
-        -k filename            True if file exists and its sticky bit is set
-        -p filename            True if file exists and is a named pipe (FIFO)
+        # If only
+        if [ arg1 operator arg2 ] ; then list
 
-        -r filename            True if file exists and is readable (has read bit set)
-        -s filename            True if file exists and has size greater than zero
-        -t fd                  True if file descriptor fd is open and refers to a terminal
-        -u filename            True if files exists and its set-user-id bit is set
-        -w filename            True if file exists and is writable
-        -x filename            True if file exists and is executable
+        # If/else
+        if [ arg1 operator arg2 ] ; then list ; else list ; fi
 
-        -G filename            True if file exists and is owned by the effective group id
-        -L filename            True if file exists and is a symbolic link
-        -N filename            True if file exists and has been modified since it was last read
-        -O filename            True if file exists and is owned by effective user id
-        -S filename            True if file exists and is a socket
 
-        file1 -ef file2        True if file1 and file2 refer to the same device and inode number
-        file1 -nt file2        True if file1 is newer, or if file1 exists and file2 does not
-        file1 -ot file2        True if file1 is older, or if file2 exists and file1 does not
+    - The square braces are the traditional Bash symbols that are equivalent to the   
+        'test' command.  
+
+        # If only
+        if test arg1 operator arg2 ; then list
+
+
+    - There is also a more recent double square bracket syntax that has a few 
+        advantages.
+
+        # If only
+        if [[ arg1 operator arg2 ]] ; then list
 
 
 
-    - String Comparison Operators
+- File Operators
 
-        Operators
-        --------------------------
-        -z string          True if length is zero
-        -n string          True if length is non-zero
+    Operators
+    ----------------------------------------------------------------------------------------
+    -a filename            True if file exists
+    -b filename            True if file exists and is block special file (ie /dev/sda1)
+    -c filename            True if file exists and is character special file (ie /dev/TTY1)
+    -d filename            True if file exists and is a directory
+    -e filename            True if file exists (same as -a)
 
-        str1 == str2       True if strings are equal
-        or                   - Second form should be used with test command
-        str1 = str2          - When used with [[ command, performs pattern matching
+    -f filename            True if file exists and is regular file
+    -g filename            True if file exists and is set-group-id, SETGID
+    -h filename            True if file exists and is symbolic link
+    -k filename            True if file exists and its sticky bit is set
+    -p filename            True if file exists and is a named pipe (FIFO)
 
-        str1 != str2       True if strings are not equal
+    -r filename            True if file exists and is readable (has read bit set)
+    -s filename            True if file exists and has size greater than zero
+    -t fd                  True if file descriptor fd is open and refers to a terminal
+    -u filename            True if files exists and its set-user-id bit is set
+    -w filename            True if file exists and is writable
+    -x filename            True if file exists and is executable
 
-        str1 < str2        True if str1 sorts before str2 lexicographically
+    -G filename            True if file exists and is owned by the effective group id
+    -L filename            True if file exists and is a symbolic link
+    -N filename            True if file exists and has been modified since it was last read
+    -O filename            True if file exists and is owned by effective user id
+    -S filename            True if file exists and is a socket
 
-        str1 > str2        True if str1 sorts after str2 lexicographically
-
-
-
-    - Numerical Comparison Operators
-
-        Operators
-        --------------------------
-        arg1 -eq arg2      Equal
-        arg1 -ne arg2      Not equal
-
-        arg1 -lt arg2      Less than
-        arg1 -le arg2      Lest than or equal to
-
-        arg1 -gt arg2      Greater than
-        arg1 -ge arg2      Greater than or equal to
+    file1 -ef file2        True if file1 and file2 refer to the same device and inode number
+    file1 -nt file2        True if file1 is newer, or if file1 exists and file2 does not
+    file1 -ot file2        True if file1 is older, or if file2 exists and file1 does not
 
 
 
-    - Miscellaneous Operators
+- String Comparison Operators
+
+    Operators
+    --------------------------
+    -z string          True if length is zero
+    -n string          True if length is non-zero
+
+    str1 == str2       True if strings are equal
+    or                   - Second form should be used with test command
+    str1 = str2          - When used with [[ command, performs pattern matching
+
+    str1 != str2       True if strings are not equal
+
+    str1 < str2        True if str1 sorts before str2 lexicographically
+
+    str1 > str2        True if str1 sorts after str2 lexicographically
+
+
+
+- Numerical Comparison Operators
+
+    Operators
+    --------------------------
+    arg1 -eq arg2      Equal
+    arg1 -ne arg2      Not equal
+
+    arg1 -lt arg2      Less than
+    arg1 -le arg2      Lest than or equal to
+
+    arg1 -gt arg2      Greater than
+    arg1 -ge arg2      Greater than or equal to
+
+
+
+- Miscellaneous Operators
 
 
 
